config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'customers', to: 'customers#index', as: 'customers'
  
  get 'customers/new', to: 'customers#new', as: 'new_customer'
  post 'customers', to: 'customers#create'
  
  get 'customers/:id/edit', to: 'customers#edit', as: 'edit_customer'
  
  patch '/customers/:id', to: 'customers#update'
  put '/customers/:id', to: 'customers#update'

  delete 'customers/:id', to: 'customers#destroy', as: 'customer'

  resources :tickets
  
  post 'tickets/:id/create', to: 'tickets#create', as: 'create_ticket'
  resources :quotes
  post 'quotes/:id/create', to: 'quotes#create', as: 'create_quote'
   
  get 'quotes/:id/quotes', to: 'quotes#quotes', as: 'customer_quote'

  get 'quotes/:id/email', to: 'quotes#email', as: 'email_quote'

  resources :products

  get 'approve_quotes/:id/edit', to: 'approve_quotes#edit', as: 'approve_quote'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :tickets
	has_many :quotes
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :quote
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	has_many :products
	belongs_to :customer
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/approve_quotes_controller.rb
class ApproveQuotesController < ApplicationController
	def edit
		@quote = Quote.find(params[:id])
		@products = @quote.products

	end

	def approve

	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
	end

	def destroy
		@customer = Customer.find(params[:id])
		@customer.destroy
		redirect_to customers_url
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])	
		@customer.update(params.require(:customer).permit(:name, :company, :phone, :email, :billing_address, :shipping_address, :taxable, :tax_location))
		redirect_to customers_url
	end

	def new
		@customer = Customer.new
	end

	def create
		Customer.create!(params.require(:customer).permit(:name, :company, :phone, :email, :billing_address, :shipping_address, :taxable, :tax_location ))	
		redirect_to customers_url
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def new
		#@quote = Quote.find(params[:id])
		#session[:quote] = @quote.id
		@quote = Quote.find(session[:edit_quote])
		@product = @quote.products.new	
	end

	def create	
		@quote = Quote.find(session[:edit_quote])
		@product = @quote.products.create!(params.require(:product).permit(:product_part))	
		
		respond_to do |format|
			format.html {redirect_to customers_url}
			format.js {
				render
				"alert('help');"
			}

		end
	end

	def index
		@products = Product.all
	end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

	def index
		@quotes = Quote.all
	end

	def quotes
		@customer = Customer.find(params[:id])
		@quotes = @customer.quotes.all		
	end

	def create
		@customer = Customer.find(params[:id])
		@quote = @customer.quotes.create!()
		redirect_to edit_quote_path(@quote)
	end

	def edit
		@quote = Quote.find(params[:id])
		session[:edit_quote] = @quote.id
		@products = @quote.products.all
		@product = Product.new
	end

	def update
		@quote = Quote.find(params[:id])	
		@quote.update(params.require(:quote).permit(:service_tech, :purpose))
		redirect_to customers_url
	end

	def destroy
		@quote = Quote.find(params[:id])
		@customer = @quote.customer
		@quote.destroy
		redirect_to customer_quote_path(@customer)
	end


	def email
		@quote = Quote.find(params[:id])
		@customer = @quote.customer
		CustomerMailer.email_quote(@customer, @quote).deliver_now
	end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	
	def index
		@tickets = Ticket.all
	end

	def create
		@customer = Customer.find(params[:id])
		@ticket = @customer.tickets.create!()
		#@request = Request.create!(description: 'sample descripton')
		#@customer.requests = @request
		#@ticket.save!
		
		redirect_to tickets_path
	end

	def edit
		@ticket = Ticket.find(params[:id])
	end

	def update
		@ticket = Ticket.find(params[:id])	
		@ticket.update(params.require(:ticket).permit(:description))
		redirect_to tickets_url
	end

	def destroy
		@ticket = Ticket.find(params[:id])
		@ticket.destroy
		redirect_to tickets_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approve_quotes_helper.rb
module ApproveQuotesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/approve_quotes/edit.html.erb
<h1>Approve Quote</h1>

<dl>
  <dt>Service Tech:</dt>
  <dd><%= @quote.service_tech %></dd>
  <dt>Purpose:</dt>
  <dd><%= @quote.purpose %></dd>
</dl>


<p>Products</p>

<section id="products-section">
<table id="products">
	<tr>
		<th>Product/Part</th>  
		<th>Unit/Mdl</th>
		<th>Description</th>  
		<th>Qty</th>
		<th>Price</th>
		<th>Total</th>  
	</tr>	
	<tbody>
		<%= render @products %>
	</tbody>
</table>
</section>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= form_for(@customer) do |f| %>

	<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
	</p>
	
	<p>
	<%= f.label :company %>
	<%= f.text_field :company %>
	</p>
	
	<p>
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	</p>
	
	<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
	</p>
	
	<p>
	<%= f.label :billing_address %>
	<%= f.text_field :billing_address %>
	</p>
	
	<p>
	<%= f.label :shipping_address %>
	<%= f.text_field :shipping_address %>
	</p>
	
	<p>
	<%= f.label :taxable %>
	<%= f.check_box :taxable %>
	</p>
	
	<p>
	<%= f.label :tax_location %>
	<%= f.text_field :tax_location %>
	</p>
	
	<p>
	<%= f.submit %>
	</p>
<% end %> 

app/views/customers/index.html.erb
<h1>Customer Index</h1>

<table>
	<tr>
		<th>Name</th> <th>Company</th> <th>Phone</th> <th>Email</th> <th>Billing Address</th> <th>Shipping Address</th> <th>Taxable</th> <th>Tax Location</th> 
	</tr>	
	<% @customers.each do |c| %>
		<tr>
			<td><%= c.name %></td>
			<td><%= c.company %></td>
			<td><%= c.phone %></td>
			<td><%= c.email %></td>
			<td><%= c.billing_address %></td>
			<td><%= c.shipping_address %></td>
			<td><%= c.taxable %></td>
			<td><%= c.tax_location %></td>
			<td>[<%= link_to "edit", edit_customer_path(c) %>] | [<%= link_to "delete", customer_path(c), method: :delete %>] | [<%= link_to "add to tickets", create_ticket_path(c), method: :post%> | [<%= link_to "Create Quote", create_quote_path(c), method: :post %>
				|[<%= link_to "Show Quotes", customer_quote_path(c) %>
			</td>
		</tr>
	<% end %>
</table>

<p>
	<%= link_to "Create Customer", new_customer_path %>
</p>

app/views/customers/new.html.erb
<h1>Create Customer</h1>

<%= form_for(@customer) do |f| %>

	<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
	</p>
	
	<p>
	<%= f.label :company %>
	<%= f.text_field :company %>
	</p>
	
	<p>
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	</p>
	
	<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
	</p>
	
	<p>
	<%= f.label :billing_address %>
	<%= f.text_field :billing_address %>
	</p>
	
	<p>
	<%= f.label :shipping_address %>
	<%= f.text_field :shipping_address %>
	</p>
	
	<p>
	<%= f.label :taxable %>
	<%= f.check_box :taxable %>
	</p>
	
	<p>
	<%= f.label :tax_location %>
	<%= f.text_field :tax_location %>
	</p>
	
	<p>
	<%= f.submit %>
	</p>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServiceManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<p>
<% if user_signed_in? %>
	<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to 'Sign In', new_user_session_path %>
<% end %>
</p>




<%= yield %>

<hr>

<% if flash[:notice] %>
	<p class="notice"><%= notice %></p>
<% end %>

<% if flash[:alert] %>
	<p class="alert"><%= alert %></p>
<% end %>
</body>
</html>

app/views/products/_product.html.erb
<tr>
	<td><%= product.product_part %></td>
	<td><%= product.unit_mdl %></td>
	<td><%= product.description %></td>
	<td><%= product.quantity %></td>
	<td><%= product.price %></td>
	<td><%= product.total %></td>
</tr>

app/views/products/create.js.erb
$("<%= escape_javascript(render @product) %>").appendTo("#products");

app/views/products/index.html.erb
<h1>All Products</h1>
<table>
	<tr>
		<th>Product/Part</th>  
		<th>Unit/Mdl</th>
		<th>Description</th>  
		<th>Qty</th>
		<th>Price</th>
		<th>Total</th>  
	</tr>	
	<% @products.each do |p| %>
		<tr>
			<td><%= p.product_part %></td>
			<td><%= p.unit_mdl %></td>
			<td><%= p.description %></td>
			<td><%= p.quantity %></td>
			<td><%= p.price %></td>
			<td><%= p.total %></td>
			
		</tr>
	<% end %>
</table>

app/views/products/new.html.erb
<h1>Add Product</h1>

<%= form_for(@product) do |p| %>

	<p>
	<%= p.label :product_part %>
	<%= p.text_field :product_part%>
	</p>
	
	<p>
	<%= p.submit %>
	</p>
<% end %> 

app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>

<%= form_for(@quote) do |q| %>

	<p>
	<%= q.label :service_tech %>
	<%= q.text_field :service_tech %>
	</p>
	
	<p>
	<%= q.label :purpose %>
	<%= q.text_field :purpose %>
	</p>
	
	<p>
	<%= q.submit %>
	</p>
<% end %>


<p>Products</p>

<section id="products-section">
<table id="products">
	<tr>
		<th>Product/Part</th>  
		<th>Unit/Mdl</th>
		<th>Description</th>  
		<th>Qty</th>
		<th>Price</th>
		<th>Total</th>  
	</tr>	
	<tbody>
		<%= render @products %>
	</tbody>
</table>

<%= form_for (@product), :remote => true do |p| %>

	<p>
	<%= p.label :product_part %>
	<%= p.text_field :product_part%>
	</p>
	
	<p>
	<%= p.submit %>
	</p>
<% end %> 


</section>
<%= link_to "Add New Product", new_product_path %>
<%= link_to "Email Quote To Customer", email_quote_path(@quote) %>

app/views/quotes/email.html.erb
<h1>Email Sent Successfully!</h1>

app/views/quotes/index.html.erb
<h1>All Quotes</h1>

<table>
	<tr>
		<th>Name</th>  
		<th>Phone</th>
		<th>Email</th>  
		<th>Shipping Address</th>
		<th>Purpose</th>  
	</tr>	
	<% @quotes.each do |q| %>
		<tr>
			<td><%= q.customer.name %></td>
			<td><%= q.customer.phone %></td>
			<td><%= q.customer.email %></td>
			<td><%= q.customer.shipping_address %></td>
			<td><%= q.purpose %></td>
			<td>[<%= link_to "edit", edit_quote_path(q) %>]</td>
		</tr>
	<% end %>
</table>

app/views/quotes/quotes.html.erb
<h1>Customer Quotes</h1>

<table>
	<tr>
		<th>Name</th>  
		<th>Phone</th>
		<th>Email</th>  
		<th>Shipping Address</th>
		<th>Purpose</th>  
	</tr>	
	<% @quotes.each do |q| %>
		<tr>
			<td><%= q.customer.name %></td>
			<td><%= q.customer.phone %></td>
			<td><%= q.customer.email %></td>
			<td><%= q.customer.shipping_address %></td>
			<td><%= q.purpose %></td>
			<td>[<%= link_to "edit", edit_quote_path(q) %>] | [<%= link_to "delete", quote_path(q), method: :delete %>]</td>
		</tr>
	<% end %>
</table>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= form_for(@ticket) do |t| %>

	<p>
		<%= t.label :description %>
		<%= t.text_area :description %>
	</p>

	<p>
		<%= t.submit %>
	</p>
<% end %> 

app/views/tickets/index.html.erb
<h1>Ticket Index</h1>

<table>
	<tr>
		<th>Name</th>  
		<th>Phone</th>
		<th>Email</th>  
		<th>Shipping Address</th>
		<th>Description</th>  
	</tr>	
	<% @tickets.each do |t| %>
		<tr>
			<td><%= t.customer.name %></td>
			<td><%= t.customer.phone %></td>
			<td><%= t.customer.email %></td>
			<td><%= t.customer.shipping_address %></td>
			<td><%= t.description %></td>
			<td>[<%= link_to "edit", edit_ticket_path(t) %>] | [<%= link_to "delete", ticket_path(t), method: :delete %>]</td>
		</tr>
	<% end %>
</table>